#!/usr/bin/env python3

__license__ = """
 File: pyharm-queue
 
 BSD 3-Clause License
 
 Copyright (c) 2020-2026, pyharm contributors
 All rights reserved.
 
 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:
 
 1. Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.
 
 2. Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.
 
 3. Neither the name of the copyright holder nor the names of its
    contributors may be used to endorse or promote products derived from
    this software without specific prior written permission.
 
 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

import os
import click
import glob
import h5py
import numpy as np

import pyharm
# Really only support kharma for now, will write abstract versions if necessary
import pyharm.io.kharma as kio
from pyharm.defs import JobReturn

@click.command()
@click.argument('op', nargs=1)
@click.argument('paths', nargs=-1, type=click.Path(exists=True))
@click.version_option(package_name='pyharm')
def queue(op, paths, **kwargs):
    """This is a utility for interacting with batch queues and KHARMA -- currently slurm-only.
    It can check up on run progress and flag stalled runs, problematic runs, and so on
    """

    # TODO
    # last file written timestamp
    # is 'final' written more recently than the last numbered restart?
    #    Is it readable?
    #    Partially written w/some zeros?
    #    Is it farther in sim time?

    # run current time (last time=)
    # run average timestep, hours to completion @ this timestep

    # Detect partial restart files

    if op == "status":
        for pathname in paths:
            path = os.path.realpath(pathname)
            print(path)
            loglist = glob.glob(os.path.join(path, "*.out"))
            if len(loglist) == 0:
                loglist = glob.glob(os.path.join(path, "*.txt"))
                if len(loglist) == 0:
                    print("No logs present!")
                    continue

            for logfile in loglist:
                lines = kio.read_stdout(logfile, -10)
                status = kio.job_status(logfile)
                print(logfile.split("/")[-1]+":", end="")
                if status == JobReturn.RUNNING:
                    print("Running")
                else:
                    print("Returned", status.name)

    # op == prep: ensure final is last-written & last in sim, link or move things otherwise

    # op == stack: submit a job from a template
    # default to naming it according to current folder
    # depend on any job running submitted from current dir




if __name__ == "__main__":
    queue()
