#!/usr/bin/env python3

__license__ = """
 File: pyharm-info
 
 BSD 3-Clause License
 
 Copyright (c) 2020-2026, pyharm contributors
 All rights reserved.
 
 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:
 
 1. Redistributions of source code must retain the above copyright notice, this
    list of conditions and the following disclaimer.
 
 2. Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.
 
 3. Neither the name of the copyright holder nor the names of its
    contributors may be used to endorse or promote products derived from
    this software without specific prior written permission.
 
 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

import os
import sys
import click
from astropy.io import ascii
from astropy.table import Table
import h5py
from pathlib import Path

import pyharm
# We're practically an io function
import pyharm.io as io
import pyharm.io.kharma as kio
import pyharm.ana.info as info
from pyharm.ana.info import SimulationDump, SimulationRun

# Count files, get times, grid sizes, MAD/SANE, fluid properties

@click.command()
@click.argument('paths', nargs=-1, type=click.Path(exists=True))
@click.option('--pars/--no-pars', help="Print a dump file's parameters and exit")
@click.option('--compare/--no-compare', help="Compare parameters of two dump files")
@click.option('-v', '--verbose', is_flag=True, help="Print extra statistics")
@click.option('--table', default="", help="Print a table of runs.  'ascii' for a text table, 'latex' for a LaTeX table")
@click.option('--table-cols', is_flag=True, help="Colums to print in the table")
@click.option('--all/--one', default=False, help="Print info on all dump files in a folder, or just one (default)")
@click.version_option(package_name='pyharm')
def info(paths, **kwargs):
    """This is a general utility for printing information about a dump, dump folder, grid file,
    or other pyharm-adjacent file.
    """
    
    # Handle --compare option
    if kwargs['compare']:
        if len(paths) != 2:
            print("Error: --compare requires exactly 2 paths")
            exit(1)
        
        info.compare_dump_pars(paths[0], paths[1])
        exit()

    if kwargs['table'] != "":
        cols = kwargs['table_cols'].split(",") if 'cols' in kwargs else ['run_name', 'resolution', 'beta_min']
        if kwargs['table'] == "latex":
            latexdict={'tabletype': 'table*',
                        'col_align': "|"+"|".join(SimulationRun.table_alignments(cols))+"|"}

        table = Table(names=SimulationRun.table_names(cols),
                      dtype=SimulationRun.table_types(cols))
        #table.set_types(SimulationRun.table_types(cols))
        for path in paths:
            try:
                table.add_row(SimulationRun(path).table_row(cols))
            except:
                pass
        ascii.write(table, sys.stdout, format=kwargs['table'])
        exit()

    # If not comparing or tabling, just print
    for path in paths:
        if ".hst" in path:
            print_hst_info(path, verbose=kwargs['verbose'])
            continue
        else:
            if os.path.isdir(path):
                print(SimulationRun(path))
                fnames = io.get_fnames(path)
            else:
                fnames = [path,]

            if kwargs['all']:
                for fname in fnames:
                    print(SimulationDump(fname))
            else:
                if kwargs['pars']:
                    # TODO if Parthenon-based file etc etc
                    with h5py.File(fnames[0]) as f:
                        print(f['/Input'].attrs['File'])
                else:
                    print(SimulationDump(fnames[0]))

if __name__ == "__main__":
    info()
