#!/usr/bin/env python3

import os, sys
import click
import glob
import psutil
import multiprocessing
import warnings

import pyharm
from pyharm.plots.frame import frame
from pyharm.util import calc_nthreads

# Use mpi4py if available, or multiprocessing
# TODO if MPI world size 1, fallback
try:
    import mpi4py
    from mpi4py import MPI
    from mpi4py.futures import MPICommExecutor, MPIPoolExecutor
    if MPI.COMM_WORLD.Get_rank() == 0:
        print("Using MPI", file=sys.stderr)
    # Use MPI unless we're alone
    use_mpi = (MPI.COMM_WORLD.Get_size() > 1)
    def do_out():
        return MPI.COMM_WORLD.Get_rank() == 0
except ImportError:
    use_mpi = False
    def do_out():
        return True

@click.command()
@click.argument('movie_types', nargs=1)
@click.argument('paths', nargs=-1, type=click.Path(exists=True))
# Common options
@click.option('-s', '--tstart', default=0., help="Start time.")
@click.option('-e', '--tend', default=1e7, help="End time.")
@click.option('-n', '--nthreads', default=None, help="Number of processes to use, if not using MPI")
# If you're invoking manually
@click.option('--fig_x', default=16, help="Figure width in inches.")
@click.option('--fig_y', default=9, help="Figure height in inches.")
@click.option('--fig_dpi', default=100, help="DPI of resulting figure.")
@click.option('-g','--plot_ghost', is_flag=True, default=False, help="Plot ghost zones.")
@click.option('-at','--at','--at_zone', 'at', default=0, help="Phi zone to plot at.")
@click.option('-sz','--sz','--size', 'size', default=None, help="Window size, in M each side of central object.")
@click.option('-sh','--sh','--shading', 'shading', default='gouraud', help="Shading: flat, nearest, gouraud.")
@click.option('--vmin', default=None, help="Colorscale minimum.")
@click.option('--vmax', default=None, help="Colorscale maximum.")
@click.option('--cmap', default='jet', help="Colormap.")
@click.option('--overlay_field', is_flag=True, help="Overlay field lines.")
@click.option('--accurate_fnames', is_flag=True, help="Name frames by 1/100M, for short runs.")
# Extras
@click.option('-r', '--resume', is_flag=True, help="Continue a previous run, by skipping existing frames")
@click.option('-d', '--debug', is_flag=True, help="Serial operation for debugging")
#@click.option('-m', '--memory_limit', default=1, help="Memory limit in GB for each process, enforced by starting total/m processes.")
def movie(movie_types, paths, **kwargs):
    """Generate movies of type MOVIE_TYPE from dumps at each of PATHS.

    "Movies" are generated as collections of frames in .png format, named frame_tXXXXXXXX.png by simulation time in M,
    and placed in a subdirectory "frames_MOVIE_TYPE" of the given PATH.  One can easily generate a single .mp4 movie
    from these using ffmpeg or similar, see 'scripts/batch/' for examples.

    Each PATH can contain dump files in any format readable by pyharm, either in the given directory or a subdirectory
    named "dumps", "dumps_kharma" or similar.

    MOVIE_TYPE can be any variable known to pyharm (see README, variables.py) or any "figure" function in figures.py.  A common
    first movie is 'log_rho', for example, which will plot phi=0 toroidal and midplane poloidal slices of the log base 10 of the
    density. The MOVIE_TYPE can be a comma-separated list without spaces, e.g. 'log_rho,traditional'

    If run within an MPI job/allocation with mpi4py installed, movie.py will attempt to use all allocated nodes to generate
    frames.  YMMV wildly with MPI installations, with mpi4py installed via pip generally a better choice than through conda.
    """
    path_dirs = [p for p in paths if os.path.isdir(p)]
    if len(path_dirs) == 0:
        # Single file argument, pass this
        path_dirs = paths
    if do_out(): print("Generating ",len(path_dirs)*len(movie_types.split(","))," movie(s)", file=sys.stderr)
    base_path = os.getcwd()
    for path in path_dirs:
        # If a path...
        if os.path.isdir(path):
            # change dir to path we want to image
            os.chdir(path)
            # Try to load known filenames
            files = pyharm.io.get_fnames(".")
        else:
            files = [path]

        # Add these so we can pass on just the args
        kwargs['movie_types'] = movie_types
        kwargs['path'] = path

        for movie_type in movie_types.split(","):
            frame_dir = "frames_" + movie_type
            os.makedirs(frame_dir, exist_ok=True)

        try:
            # Load diagnostics from HARM itself
            fname = glob.glob("*.hst")[0]
            if do_out(): print("Loading diag file {}".format(fname), file=sys.stderr)
            diag = pyharm.io.read_log(fname)
        except (IndexError, IOError):
            diag = None

        if do_out(): print("Imaging model {} with movie {}".format(path, movie_type), file=sys.stderr)
        if 'debug' in kwargs and kwargs['debug']:
            # Import profiling only if used, start it
            import cProfile, pstats, io
            from pstats import SortKey
            from pympler import tracker
            pr = cProfile.Profile()
            pr.enable()
            # Run sequentially to make profiling & backtraces work
            for fname in files:
                tr = tracker.SummaryTracker()
                frame(fname, diag, kwargs)
                tr.print_diff()
            
            pr.disable()
            s = io.StringIO()
            ps = pstats.Stats(pr, stream=s).sort_stats(SortKey.TIME)
            ps.print_stats(10)
            print(s.getvalue())

        else:
            # Suppress math warnings for e.g. log(-)
            if not sys.warnoptions:
                warnings.simplefilter("ignore")
            # Try to guess how many processes before we MemoryError out
            if 'nthreads' not in kwargs or kwargs['nthreads'] is None:
                if 'memory_limit' in kwargs and kwargs['memory_limit'] is not None:
                    hdr = pyharm.io.read_hdr(files[0])
                    nthreads = min(calc_nthreads(hdr, pad=0.6),
                                psutil.cpu_count())
                else:
                    nthreads = psutil.cpu_count()
            # This application is entirely side-effects (frame creation)
            # So we map & ignore result
            # TODO pass single figure & blit/encode within Python?
            if not use_mpi:
                print("Using {} processes".format(nthreads))
                with multiprocessing.Pool(nthreads) as pool:
                    args = zip(files, (diag,)*len(files), (kwargs,)*len(files))
                    pool.starmap_async(frame, args).get(720000)
            else:
                # Everything is set by MPI.  We inherit a situation and use it
                with MPICommExecutor() as executor:
                    if executor is not None:
                        print("Imaging {} files across pool size {}".format(len(files), MPI.COMM_WORLD.Get_size()), file=sys.stderr)
                        executor.map(frame, files, (diag,)*len(files), (kwargs,)*len(files))
        if do_out(): print("Imaged model {} with movie(s) {}".format(path, movie_types), file=sys.stderr)

        # Change back to wherever our root was, argument paths can be relative
        os.chdir(base_path)

if __name__ == "__main__":
    movie()
