#!/usr/bin/env python3

import sys
from pyharm import io

pref_iharm3d = False
for folder in sys.argv[1:]:
    if folder == "-iharm":
        pref_iharm3d = True
    else:
        print(folder, len(io.get_fnames(folder)))