#!/usr/bin/env python3

"""
Plot the differences between two GRMHD output files and test for similarity
"""

import pyharm
from pyharm import parameters
import pyharm.plots.plot_dumps as pplt
import pyharm.util as util

import sys
import click
import numpy as np
import matplotlib.pyplot as plt

@click.command()
@click.argument('dump1file', nargs=1, type=click.Path(exists=True))
@click.argument('dump2file', nargs=1, type=click.Path(exists=True))
# Common options
@click.option('-o', '--out_name', default=None, help="Base name of output images.")
@click.option('-g', '--ghost_zones', is_flag=True, help="Compare ghost zones.")
@click.option('--fig_x', default=20.0, help="Figure width in inches.")
@click.option('--fig_y', default=20.0, help="Figure height in inches.")
@click.option('--xmin', default=None, help="Window X minimum.")
@click.option('--xmax', default=None, help="Window X maximum.")
@click.option('--ymin', default=None, help="Window Y minimum.")
@click.option('--ymax', default=None, help="Window Y maximum.")
@click.option('--bh', default=True, help="Whether to show the BH shadow.")
@click.option('--array', is_flag=True, help="Use array coordinates")
@click.option('--vmax', default=None, help="Max comparison plot value")
@click.option('-a', '--absolute', is_flag=True, help="Plot absolute differences, rather than relative.")
@click.option('--rel_tol', default=5e-10, help="Relative tolerance to consider a variable different.")
@click.option('--abs_tol', default=1e20, help="Absolute tolerance to consider a variable different.")
@click.option('--geometry', is_flag=True, help="Compare domain sizes & shapes.")
def diff(dump1file, dump2file, **kwargs):
    if kwargs['out_name'] is not None:
        imname = kwargs['out_name']
    else:
        imname = "diff_"+'.'.join(dump1file.split('.')[:-1])+'.'.join(dump2file.split('.')[:-1])

    dump1 = pyharm.load_dump(dump1file, ghost_zones=kwargs['ghost_zones'])
    #Hopefully this fails for dumps that shouldn't be compared
    dump2 = pyharm.load_dump(dump2file, ghost_zones=kwargs['ghost_zones'])

    vars = ['RHO', 'UU', 'U1', 'U2', 'U3'] #list(dump2['prim_names']) # Parthenon isn't dealing with KEL

    kwargs['vmin'] = 0 # Making plots without this is irresponsible
    if 'vmax' not in kwargs and not kwargs['absolute']:
        kwargs['vmax'] = 1

    if kwargs['array']:
        kwargs['native'] = True
        kwargs['shading'] = 'flat'
        kwargs['half_cut'] = True
        kwargs['window'] = None

    return_code = 0

    # Always do XZ
    fig, _ = plt.subplots(3, 3, figsize=(kwargs['fig_x'], kwargs['fig_y']))
    axes = fig.get_axes()
    for var, ax in zip(vars, axes):
        if kwargs['absolute']:
            pplt.plot_diff_xz(ax, dump1, dump2, var, rel=False, **kwargs)
        else:
            pplt.plot_diff_xz(ax, dump1, dump2, var, rel=True, **kwargs)
        ax.set_xlabel('')
        ax.set_ylabel('')

        l1_norm = np.sum(np.abs(dump1[var] - dump2[var])) / np.sum(np.abs(dump1[var]))
        if l1_norm > kwargs['rel_tol']:
            print("Outputs disagree in {}: normalized L1: {}".format(var, l1_norm))
            return_code = 1

    plt.tight_layout()
    plt.savefig(imname+"_xz.png", dpi=100)
    plt.close(fig)

    # Do XY if not 2D
    if dump1['n3'] > 1:
        fig, _ = plt.subplots(3, 3, figsize=(kwargs['fig_x'], kwargs['fig_y']))
        axes = fig.get_axes()
        for var,ax in zip(vars, axes):
            if kwargs['absolute']:
                pplt.plot_diff_xy(ax, dump1, dump2, var, rel=False, **kwargs)
            else:
                pplt.plot_diff_xy(ax, dump1, dump2, var, rel=True, **kwargs)
            ax.set_xlabel('')
            ax.set_ylabel('')

        plt.tight_layout()
        plt.savefig(imname+"_xy.png", dpi=100)
        plt.close(fig)

    if kwargs['geometry']:
        print(dump1.grid.startx, dump2.grid.startx)
        print(dump1.grid.stopx, dump2.grid.stopx)
        print(dump1.grid.dx, dump2.grid.dx)
        print(dump1.params['a'], dump2.params['a'])
        if 'hslope' in dump1.params:
            print(dump1.params['hslope'], dump2.params['hslope'])
        if 'mks_smooth' in dump1.params:
            print(dump1.params['mks_smooth'], dump2.params['mks_smooth'])
            print(dump1.params['poly_xt'], dump2.params['poly_xt'])
            print(dump1.params['poly_alpha'], dump2.params['poly_alpha'])
            print(dump1.params['poly_norm'], dump2.params['poly_norm'])

    exit(return_code)

if __name__ == "__main__":
    diff()
